import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Karanjit_Singh' at '9/2/17 4:58 PM' with Gradle 3.1
 *
 * @author Karanjit_Singh, @date 9/2/17 4:58 PM
 */
public class NameFromFile {

        public boolean ifFileExists(String fileName) {

            Path file = Paths.get(fileName);
            byte[] fileArray;
            try {
                fileArray = Files.readAllBytes(file);
            } catch (IOException e) {
                System.out.println("IO exception happen");
                return false;
            }
            return true;
        }

        public String readContentsFromFile(String fileName) {
            Path file = Paths.get(fileName);
            byte[] fileArray = null;
            try {
                fileArray = Files.readAllBytes(file);
            } catch (IOException e) {
                e.printStackTrace();
            }
            return new String(fileArray);
        }


    public static void main (String[] args){

        NameFromFile nameFromFile = new NameFromFile();
        boolean result = nameFromFile.ifFileExists("C:\\Users\\Karanjit_Singh\\qa_auto_training\\java_programs\\NamesFromFile\\src\\main\\java\\test");
        String fileContent = nameFromFile.readContentsFromFile("C:\\Users\\Karanjit_Singh\\qa_auto_training\\java_programs\\NamesFromFile\\src\\main\\java\\test");
        System.out.println(fileContent);

    }
}
