import org.omg.CORBA.Object;
import org.testng.annotations.*;
import static org.testng.Assert.assertTrue;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library --with testng'
 * by 'Karanjit_Singh' at '9/2/17 4:58 PM' with Gradle 3.1
 *
 * @author Karanjit_Singh, @date 9/2/17 4:58 PM
 */
public class DoesFileHasContents {
    @DataProvider(name="contentsFromFile")
    private Object [][] contents(){
        return new Object[][] {{""}
                {"karan"}
                {"karanjit"}
    }

    }


    @Test (dataProvider = "contentsFromFile")
    public void DoesFileHasContents() {
        NameFromFile classUnderTest = new NameFromFile();
        Boolean fi = classUnderTest.ifFileExists(String filename);
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
